services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: "analyser/riskanalytics-frontend"
    environment:
      - BUILD_VERSION=${BUILD_VERSION:-1.0.0}
    ports:
      - "8053:8053"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - VERSION=${VERSION:-1.0.0.0}
    image: "analyser/riskanalytics-api"
    environment:
      - BUILD_VERSION=${BUILD_VERSION:-1.0.0}
    ports:
      - "8054:8054"
